### ISSUE TITLE
编译出现错误。

### ISSUE THREAD

**Issue by BigBookPlus** [qiniudemo/c-sdk-demo#1]
vs2015+最新预编译win下SDK，编译不过。

![image](https://user-images.githubusercontent.com/5856148/41462149-7889da5e-70c4-11e8-9a47-58c5f17e51e1.png)

**Comment by jemygraw** [comment]
你选中解决方案，然后右键，看看菜单里面有没有一个。
![image](https://user-images.githubusercontent.com/1751166/41573362-e92495dc-73ae-11e8-98aa-95f1f339c5eb.png)

**Comment by jemygraw** [comment]
另外还需要去下载 https://github.com/qiniu/c-sdk-for-windows 然后调整下include path和library path的路径。

**Comment by jemygraw** [comment]
![c-sdk-demo-include](https://user-images.githubusercontent.com/1751166/41581985-eed9807c-73d2-11e8-9bc6-1277b313c66d.png)

**Comment by jemygraw** [comment]
![c-sdk-demo-lib](https://user-images.githubusercontent.com/1751166/41582056-19e6840e-73d3-11e8-93df-ee8f8a05c70b.png)
